### ISSUE TITLE
Deadlines

### ISSUE THREAD

**Issue by HugoNikanor** [vim-advent-calendar/ideas#10]
The deadlines for pledges, articles, and so on isn't anywhere in the repo as far as I can see.

They should be added here, and not forgotten in a Reddit post.

**Comment by HugoNikanor** [comment]
I added them to the README.

*Actually I thought that the push would create a pull request. But I apparently had push access.*

**Comment by romainl** [comment]
Yeah, all the members of the org have push access.

**Comment by robertmeta** [comment]
Thanks @HugoNikanor !
