### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by samuelallan72** [vim-advent-calendar/ideas#13]
I'd appreciate some feedback on my idea before I go much further. Specifically, is this going to be too broad/long/short/boring/etc., is describing vim and git workflows and tip and tricks going to be interesting, and what should I add/remove? Thanks :)

https://github.com/vim-advent-calendar/ideas/blob/master/swalladge-vim-and-git.md

**Comment by romainl** [comment]
I'll give it a read later today.

**Comment by romainl** [comment]
* ":GV" is https://github.com/junegunn/gv.vim, right?
* "vim-fugitive with mergetool" should be an interesting topic. Not sure where to put it either but why not write it right there and see later?
* This may seem incredibly obvious, but I've seen jaws drop while using `$ git commit -v` and then plain keyword/line completion to craft useful commit messages.
* Interactive rebasing with Vim is a joy. And the more commit lines, the better it feels.
* Do you have experience with all those plugins? Are they all part of your workflow?

**Comment by samuelallan72** [comment]
>     * ":GV" is https://github.com/junegunn/gv.vim, right?

Correct.

>     * "vim-fugitive with mergetool" should be an interesting topic. Not sure where to put it either but why not write it right there and see later?

Ok :+1:

>     * This may seem incredibly obvious, but I've seen jaws drop while using `$ git commit -v` and then plain keyword/line completion to craft useful commit messages.
> 
>     * Interactive rebasing with Vim is a joy. And the more commit lines, the better it feels.

Agreed, but I've only ever had to do that maybe twice in the last 4 years... I
don't feel very able to write about it. :/

>     * Do you have experience with all those plugins? Are they all part of your workflow?

I have tried out pretty much all, and many still play a part in my scattered
workflow. For example, I'll use gv.vim to find a commit sometimes when in vim,
but tig when I'm in a terminal. That's one of the issues I'm having: I don't
feel my workflow(s) are tidy enough to write neatly about. Perhaps that is
going to dictate the structure of the article (eg. a bunch of useful aspects of
many different things instead of a discussion on how things fit in a workflow).

Thanks for the review! :)

**Comment by samuelallan72** [comment]
Sorry for the delay; life has been busy recently. I'm madly working on it now. Hopefully it's not going to be too late?

**Comment by romainl** [comment]
Don't worry, we are all very very late. Thank you for your dedication.
