### ISSUE TITLE
Tags Feedback

### ISSUE THREAD

**Issue by djmoch** [vim-advent-calendar/ideas#15]
I know we're kind of down to the wire here, but I've finished drafting my article (complete as of 7975c2b26c6fbf3d87c21140e5bf670aa6573c0f). If anyone has some spare cycles today to take a look and provide feedback, I'll be happy to incorporate.

**Comment by romainl** [comment]
Hi, I've copied your document over here: https://github.com/vim-advent-calendar/vimways.org/blob/master/content/2018/djmoch-tag-vims-it.md and added a front matter. Could you fill the description?

As for comments I only have one and it's tiny: I was expecting a mention of task runners and filesystem watchers in the "automatic" section. I don't feel it's necessary but it would make it more "whole", IMO.

**Comment by djmoch** [comment]
Sounds good. I’ll take care of the description and I’ll address your comment when I get back to my machine later tonight (I’m US/Eastern, so it could be a couple hours yet).
