### ISSUE TITLE
Create topic ideas to help authors along if they don't have an idea of their own.

### ISSUE THREAD

**Issue by romainl** [vim-advent-calendar/ideas#2]
Set up best practices
Multi-platform set up
Learning path
Interaction with the environment
Using Vim for weird things (music, statistical analysis, etc.)
When to look for a plugin
What to look for in a plugin
Editing best practices
Vimscript is not that bad|hard
Debunking common misconceptions
List valuable resources
How did they do it before XXX?

**Comment by robertmeta** [comment]
To quote you from Reddit.

Thank you for your interest.

Content-wise, here is a quick and dirty list of writing prompts (that mostly tell about my own interests, not an exhaustive or prescriptive list by any means):

best practices for your setup

make your setup truly cross-platform

the ideal learning path

how to integrate vim with its environment

using Vim for weird things (music, statistical analysis, painting, etc.)

when to look for a plugin

what to look for in a plugin

editing best practices

vimscript is not that bad/hard

debunking common misconceptions

listing valuable resources (and explaining why they are valuable)

everything you never thought you wanted to know about $FEATURE

let me talk to you about my convoluted way to become a vimmer

state of the nation

long-term trends in plugin design (async, lsp, etc.)

a view at operators from a linguistics point of view

when is vim everywhere too much

history behind $DESIGN_CHOICE

and another list of things we don't want unless they improve a lot on their respective archetypes:

vim as an IDE

lists of plugins

you absolutely need my config

and I mean a lot.

Length-wise, I would say anything above 1,500 words is fine but, as u/robertmeta hinted at, an asciinema embed or a comic would work, too.

Quality-wise, the more you know your stuff the better, but we will certainly take a critical look at your production. Don't apply if you can't handle that kind of pressure.

ROI-wise, there's no personal gain to make from any of that unless you count online reputation as personal gain: no ad money to share, no cocaine, no bitches, no place in heaven. If there's anything to gain from that effort it would be a better average quality of Vim content available to new users.
