### ISSUE TITLE
Deep vs. Wide

### ISSUE THREAD

**Issue by robertmeta** [vim-advent-calendar/ideas#5]
We are going to have (at least) 24 articles.  I went overload broad in my topic choice. 

Focus on something.  So far we got:

- Opening Files
- Integration with external tools
- Formatting with vim
- Why you want ONE instance of vim

These three are GREAT.  I will leave this as a reminder to myself and others not to go overly broad in topic choices!

**Comment by romainl** [comment]
I generally agree on the superiority of deep over wide but our main topic at hand, Vim, is already pretty narrow.

I can see a future for our little project where we provide a theme to the participants, though, much like they do in game design marathons and demo contests.

* Theme for 201X: hand-eye coordination
* Theme for 201X+1: Vim for kids
* Theme for 201X+2: foobar baz

**Comment by robertmeta** [comment]
Yeah, my point was more we don't want like 4x "How I setup my vim" -- which I have gotten a lot of inquires about that style of article.
